export const CSI_DIVISIONS = {
  "01": "General Requirements",
  "02": "Existing Conditions",
  "03": "Concrete",
  "04": "Masonry",
  "05": "Metals",
  "06": "Wood, Plastics, and Composites",
  "07": "Thermal and Moisture Protection",
  "08": "Openings",
  "09": "Finishes",
  "10": "Specialties",
  "11": "Equipment",
  "12": "Furnishings",
  "13": "Special Construction",
  "14": "Conveying Equipment",
  "21": "Fire Suppression",
  "22": "Plumbing",
  "23": "HVAC",
  "25": "Integrated Automation",
  "26": "Electrical",
  "27": "Communications",
  "28": "Electronic Safety and Security",
  "31": "Earthwork",
  "32": "Exterior Improvements",
  "33": "Utilities",
  "34": "Transportation",
  "35": "Waterway and Marine Construction",
  "40": "Process Integration",
  "41": "Material Processing and Handling Equipment",
  "42": "Process Heating, Cooling, and Drying Equipment",
  "43": "Process Gas and Liquid Handling, Purification and Storage Equipment",
  "44": "Pollution Control Equipment",
  "45": "Industry-Specific Manufacturing Equipment",
  "46": "Water and Wastewater Equipment",
  "48": "Electrical Power Generation",
  "49": "Water Treatment and Wastewater Treatment Equipment",
  "50": "Basic Material and Processed Material",
  "51": "Basic Metal Materials and Methods",
  "52": "Nonferrous Metal Materials and Methods",
  "53": "Metal Material Methods and Fasteners",
  "54": "Metal Finishing and Cleaning",
  "55": "Metal Fabrication and Assemblies",
  "56": "Reservoirs and Water Storage",
  "57": "Reservoirs and Water Storage",
  "58": "Reservoirs and Water Storage",
  "59": "Reservoirs and Water Storage",
  "60": "Reservoirs and Water Storage",
  "61": "Reservoirs and Water Storage",
  "62": "Reservoirs and Water Storage",
  "63": "Reservoirs and Water Storage",
  "64": "Reservoirs and Water Storage",
  "65": "Reservoirs and Water Storage",
  "66": "Reservoirs and Water Storage",
  "67": "Reservoirs and Water Storage",
  "68": "Reservoirs and Water Storage",
  "69": "Reservoirs and Water Storage",
  "70": "Reservoirs and Water Storage",
  "71": "Reservoirs and Water Storage",
  "72": "Reservoirs and Water Storage",
  "73": "Reservoirs and Water Storage",
  "74": "Reservoirs and Water Storage",
  "75": "Reservoirs and Water Storage",
  "76": "Reservoirs and Water Storage",
  "77": "Reservoirs and Water Storage",
  "78": "Reservoirs and Water Storage",
  "79": "Reservoirs and Water Storage",
  "80": "Reservoirs and Water Storage",
  "81": "Reservoirs and Water Storage",
  "82": "Reservoirs and Water Storage",
  "83": "Reservoirs and Water Storage",
  "84": "Reservoirs and Water Storage",
  "85": "Reservoirs and Water Storage",
  "86": "Reservoirs and Water Storage",
  "87": "Reservoirs and Water Storage",
  "88": "Reservoirs and Water Storage",
  "89": "Reservoirs and Water Storage",
  "90": "Reservoirs and Water Storage",
  "91": "Reservoirs and Water Storage",
  "92": "Reservoirs and Water Storage",
  "93": "Reservoirs and Water Storage",
  "94": "Reservoirs and Water Storage",
  "95": "Reservoirs and Water Storage",
  "96": "Reservoirs and Water Storage",
  "97": "Reservoirs and Water Storage",
  "98": "Reservoirs and Water Storage",
  "99": "Reservoirs and Water Storage"
} 